# require 'csv'
# require 'awesome_print'
#
# csv_text = File.read(Rails.root.join('lib', 'seeds', 'brain.csv'))
# csv = CSV.parse(csv_text, headers: true, encoding: 'iso-8859-1:utf-8')
#
# csv.each do |row|
#   t = Brain.new
#   t.ProductName = row["ProductName"]
#   t.CSF = row["CSF"]
#   t.CompanyName = row["CompanyName"]
#   t.BrandName = row["BrandName"]
#   t.PrimaryCategory = row["PrimaryCategory"]
#   t.SubCategory = row["SubCategory"]
#   t.ChemicalName = row["ChemicalName"]
#   t.save
# end
#
# puts "There are now #{Brain.count} rows in the database"

Brand.create([
  {BrandName: "10 Corso Como"},
  {BrandName: "2 Cruel"},
  {BrandName: "3D Aquarium Hand Soap"},
  {BrandName: "4 East Cosmetics"},
  {BrandName: "ABCO "},
  {BrandName: "ABI"},
  {BrandName: "ABSOLUTE FX"},
  {BrandName: "Acca"},
  {BrandName: "ACNE FREE"},
  {BrandName: "ACT"},
  {BrandName: "Adidas"},
  {BrandName: "Advanced Keratin System"},
  {BrandName: "AffClean"},
  {BrandName: "Affirm"},
  {BrandName: "AG"},
  {BrandName: "Age Beautiful"},
  {BrandName: "Ageless Reflection"},
  {BrandName: "Ahold"},
  {BrandName: "Airspun"},
  {BrandName: "Alba Botanica"},
  {BrandName: "ALE Colour Gels"},
  {BrandName: "Alessandro International"},
  {BrandName: "Alfalfa Nail Supply, Inc."},
  {BrandName: "Algas Marinas Body Firming Gel "},
  {BrandName: "All Hands"},
  {BrandName: "All That Jazz"},
  {BrandName: "Allegro Bosy Wash"},
  {BrandName: "Allow"},
  {BrandName: "Almay"},
  {BrandName: "ALOE LAND"},
  {BrandName: "Aloe Up"},
  {BrandName: "Aloette"},
  {BrandName: "Alpha Hydrox"},
  {BrandName: "ALQVIMIA - Essentially Beautiful"},
  {BrandName: "Altcheck MD"},
  {BrandName: "ALTER EGO ITALY"},
  {BrandName: "Alyssa Ashley"},
  {BrandName: "Amatokin"},
  {BrandName: "AMBI"},
  {BrandName: "AMERI BEAUTY"},
  {BrandName: "America's Choice"},
  {BrandName: "America's Next Top Model"},
  {BrandName: "American Beauty"},
  {BrandName: "American Choice"},
  {BrandName: "American Fare"},
  {BrandName: "Amope "},
  {BrandName: "AMOREPACIFIC"},
  {BrandName: "Amway Global"},
  {BrandName: "Anastasia Beverly Hills"},
  {BrandName: "Andrea"},
  {BrandName: "Annemarie Brlind"},
  {BrandName: "APLICARE"},
  {BrandName: "April Bath & Shower"},
  {BrandName: "ApriVera"},
  {BrandName: "Aquafina"},
  {BrandName: "Aquamer"},
  {BrandName: "Arbonne Cosmetics"},
  {BrandName: "ARCHIPELAGO"},
  {BrandName: "Archive"},
  {BrandName: "Ardell"},
  {BrandName: "Arissa"},
  {BrandName: "ARITAUM"},
  {BrandName: "ARITAUM "},
  {BrandName: "Armand Dupree"},
  {BrandName: "aromappeal"},
  {BrandName: "Aromassentials"},
  {BrandName: "Arroz Polvo Sellador / Rice Setting Powder"},
  {BrandName: "Artistic"},
  {BrandName: "Artistic Nail Design "},
  {BrandName: "Artistry"},
  {BrandName: "Artmatic"},
  {BrandName: "Artra"},
  {BrandName: "Assured"},
  {BrandName: "Astara Skin Care"},
  {BrandName: "Aubrey Organics"},
  {BrandName: "Australian Gold"},
  {BrandName: "Avalon Organics"},
  {BrandName: "Aveda"},
  {BrandName: "AVEENO"},
  {BrandName: "Aviance Night Musk"},
  {BrandName: "AVOJUICE"},
  {BrandName: "AVON"},
  {BrandName: "Axe"},
  {BrandName: "axxium"},
  {BrandName: "axxium Soak-Off"},
  {BrandName: "Ayur"},
  {BrandName: "Ayurmedic"},
  {BrandName: "AZIZA"},
  {BrandName: "AZZARO"},
  {BrandName: "Baba de Caracol"},
  {BrandName: "BABOR"},
  {BrandName: "Baby Phat "},
  {BrandName: "Back to Basics"},
  {BrandName: "Bain de Terre"},
  {BrandName: "Bakugan"},
  {BrandName: "Balmex"},
  {BrandName: "Banana Boat"},
  {BrandName: "Bandito"},
  {BrandName: "Barbie"},
  {BrandName: "Barburys"},
  {BrandName: "bareEscentuals"},
  {BrandName: "bareMinerals"},
  {BrandName: "bareVitamins"},
  {BrandName: "Barielle"},
  {BrandName: "Basis"},
  {BrandName: "Bath & Body Works"},
  {BrandName: "BATH GEL PACKET"},
  {BrandName: "Bathe Away"},
  {BrandName: "Bay Bay Blemish"},
  {BrandName: "Baymont"},
  {BrandName: "BC (BeautiControl) Color"},
  {BrandName: "BC (BeautiControl) Color Freeze"},
  {BrandName: "BC (BeautiControl) Margarita Body"},
  {BrandName: "BC (BeautiControl) Platinum Regeneration"},
  {BrandName: "BC (BeautiControl) Regeneration"},
  {BrandName: "BCBG"},
  {BrandName: "Beach Buff Reef Safe"},
  {BrandName: "Beautique "},
  {BrandName: "Beauty Calssics"},
  {BrandName: "BEAUTY EFFEX"},
  {BrandName: "BEAUTY IMAGE"},
  {BrandName: "Beauty Secrets"},
  {BrandName: "BEAUTY SOCIETY"},
  {BrandName: "BEAUTY TREATS"},
  {BrandName: "Beauty360"},
  {BrandName: "Beautycode Switzerland"},
  {BrandName: "BEBE"},
  {BrandName: "Bechic"},
  {BrandName: "Bed Head"},
  {BrandName: "Bed Head Colour Combat"},
  {BrandName: "Bed Head Styleshots"},
  {BrandName: "Before Sun"},
  {BrandName: "BEING TRUE"},
  {BrandName: "Being Well"},
  {BrandName: "Benefit Cosmetics"},
  {BrandName: "Benev"},
  {BrandName: "Best Choice"},
  {BrandName: "BESTWE"},
  {BrandName: "Betco"},
  {BrandName: "Beyonce Heat"},
  {BrandName: "Beyonce Heat Rush"},
  {BrandName: "Beyonce Midnight Heat"},
  {BrandName: "Beyonce Pulse"},
  {BrandName: "Beyond"},
  {BrandName: "Beyond Belief"},
  {BrandName: "Beyond the Zone"},
  {BrandName: "Big Sexy Hair"},
  {BrandName: "Big Sexy Hair "},
  {BrandName: "Bigen"},
  {BrandName: "BILQIS WAX"},
  {BrandName: "BIO PROGRAM"},
  {BrandName: "Bio-Groom"},
  {BrandName: "Bioelements"},
  {BrandName: "Biogenol"},
  {BrandName: "Bioglitz"},
  {BrandName: "Bioglo"},
  {BrandName: "BIOLOGIQUE RECHERCHE"},
  {BrandName: "Bior"},
  {BrandName: "BioSilk"},
  {BrandName: "BioTouch"},
  {BrandName: "Bitzy"},
  {BrandName: "Black & White"},
  {BrandName: "Black Up"},
  {BrandName: "Bliss"},
  {BrandName: "Blistex"},
  {BrandName: "Blue Cat Body Wash"},
  {BrandName: "Blue Goo"},
  {BrandName: "Blue Lagoon"},
  {BrandName: "Bobbi Brown"},
  {BrandName: "body by BRIGITTE"},
  {BrandName: "Body Drench"},
  {BrandName: "BODY ECLIPSE"},
  {BrandName: "Body Essence"},
  {BrandName: "Body Fantasies"},
  {BrandName: "Body High Spa"},
  {BrandName: "Body Prescriptions"},
  {BrandName: "Body Raves"},
  {BrandName: "Bonne Bell"},
  {BrandName: "Bonvivant"},
  {BrandName: "Boots Botanics"},
  {BrandName: "Bora Bora"},
  {BrandName: "Borboleta"},
  {BrandName: "Borghese"},
  {BrandName: "Botanical Effects"},
  {BrandName: "Bratz"},
  {BrandName: "Brazilian Blowout"},
  {BrandName: "Breck Kids"},
  {BrandName: "Bremenn Research Labs"},
  {BrandName: "Britney Spears"},
  {BrandName: "BROADWAY"},
  {BrandName: "Brocato"},
  {BrandName: "BullFrog"},
  {BrandName: "Burt's Bees"},
  {BrandName: "BUXOM"},
  {BrandName: "BVLGARI"},
  {BrandName: "BY Framesi"},
  {BrandName: "by Jodi Crissy"},
  {BrandName: "Bye Bye Blemish"},
  {BrandName: "CALI CHEM"},
  {BrandName: "California Baby"},
  {BrandName: "CALIFORNIA MANGO"},
  {BrandName: "California North"},
  {BrandName: "California Tan"},
  {BrandName: "California Tan/Matahari"},
  {BrandName: "Calvin Klein"},
  {BrandName: "Calvin Klein Beauty"},
  {BrandName: "Calvin Klein CK Free"},
  {BrandName: "Calvin Klein CK One "},
  {BrandName: "Calvin Klein CKIN2U"},
  {BrandName: "Calvin Klein Dark Obsession"},
  {BrandName: "Calvin Klein Escape"},
  {BrandName: "Calvin Klein Eternity"},
  {BrandName: "Calvin Klein Euphoria"},
  {BrandName: "Calvin Klein Man"},
  {BrandName: "Calvin Klein Obsession"},
  {BrandName: "Camelback"},
  {BrandName: "Candies"},
  {BrandName: "Cardinal Health"},
  {BrandName: "Care One"},
  {BrandName: "Caress"},
  {BrandName: "CARITA"},
  {BrandName: "Carolina Herrera"},
  {BrandName: "Casually Yours"},
  {BrandName: "Catwalk"},
  {BrandName: "CB Smoothe"},
  {BrandName: "Celestial Body"},
  {BrandName: "Celine Dion"},
  {BrandName: "Celine Dion Chic"},
  {BrandName: "Celine Dion Enchanting"},
  {BrandName: "Celine Dion Pure Radiance"},
  {BrandName: "Celine Dion Sensational"},
  {BrandName: "Cera Di Cupra"},
  {BrandName: "Ceramic Glaze"},
  {BrandName: "Champneys"},
  {BrandName: "CHANEL"},
  {BrandName: "Chantecaille"},
  {BrandName: "Charlotte Tilbury"},
  {BrandName: "Checi"},
  {BrandName: "CHI"},
  {BrandName: "China Glaze"},
  {BrandName: "China Glaze Gelaze"},
  {BrandName: "Choice"},
  {BrandName: "Christian Dior"},
  {BrandName: "Christine Ashley"},
  {BrandName: "ChristineChin"},
  {BrandName: "Chromatic"},
  {BrandName: "Chrome Hearts"},
  {BrandName: "Circa"},
  {BrandName: "Circle of Friends"},
  {BrandName: "Claiborne"},
  {BrandName: "Claire's"},
  {BrandName: "Clairol Balsam"},
  {BrandName: "Clairol Hydrience"},
  {BrandName: "Clairol Professional Complements"},
  {BrandName: "Clairol Professional Mix Tones"},
  {BrandName: "Clairol Professional Premium Creme"},
  {BrandName: "CLARINS"},
  {BrandName: "CLARINS PARIS"},
  {BrandName: "Clario"},
  {BrandName: "Clarite"},
  {BrandName: "Classic"},
  {BrandName: "Classic Touch"},
  {BrandName: "Claudia Stevens"},
  {BrandName: "Cle de peau beaute"},
  {BrandName: "CLEAN & CLEAR"},
  {BrandName: "Clean + Easy"},
  {BrandName: "Clear"},
  {BrandName: "Clearasil"},
  {BrandName: "Clinique"},
  {BrandName: "Cliniscalp"},
  {BrandName: "Cliven"},
  {BrandName: "CloSYS"},
  {BrandName: "Clubman"},
  {BrandName: "CND"},
  {BrandName: "Coach"},
  {BrandName: "Coast"},
  {BrandName: "COCO BEACH"},
  {BrandName: "Coconut Kiss"},
  {BrandName: "Colgate"},
  {BrandName: "Collab"},
  {BrandName: "Color Club"},
  {BrandName: "Color Fun"},
  {BrandName: "Color Naturals"},
  {BrandName: "Color Secret"},
  {BrandName: "Colorescience"},
  {BrandName: "COMPAGNIA DEL COLORE"},
  {BrandName: "Competition"},
  {BrandName: "Connemara"},
  {BrandName: "Cool Cuts 4 Kids"},
  {BrandName: "Coppertone"},
  {BrandName: "Correctionist"},
  {BrandName: "Corrector Do"},
  {BrandName: "Cortizone 10"},
  {BrandName: "Cos. Brands Anti-Aging Mineral"},
  {BrandName: "CosMedix"},
  {BrandName: "CosMedix "},
  {BrandName: "Costcutters"},
  {BrandName: "Couleurs Nature"},
  {BrandName: "Cover FX"},
  {BrandName: "Cover Your Gray"},
  {BrandName: "Coverblend by Exuviance"},
  {BrandName: "CoverGirl"},
  {BrandName: "CQ"},
  {BrandName: "Crabtree & Evelyn"},
  {BrandName: "Crayola"},
  {BrandName: "Create Professional"},
  {BrandName: "Creative"},
  {BrandName: "Crest"},
  {BrandName: "Crystal Waters"},
  {BrandName: "CULTURE BIO NUTRITION"},
  {BrandName: "Cupra Light"},
  {BrandName: "Curl"},
  {BrandName: "Curve"},
  {BrandName: "Cutie Boutique"},
  {BrandName: "CUTIE GIRL"},
  {BrandName: "CVS"},
  {BrandName: "D&R"},
  {BrandName: "Daisy Fuentes"},
  {BrandName: "Darphin"},
  {BrandName: "DASHING DIVA"},
  {BrandName: "Davines"},
  {BrandName: "Daylogic"},
  {BrandName: "Days Inn"},
  {BrandName: "DaySpring Inc."},
  {BrandName: "DC Comics"},
  {BrandName: "DC Suicide Squad"},
  {BrandName: "de la Ritz"},
  {BrandName: "Dead Sea"},
  {BrandName: "Deb"},
  {BrandName: "Deborah Lippmann"},
  {BrandName: "DECLEOR"},
  {BrandName: "DECORT"},
  {BrandName: "Degree"},
  {BrandName: "Del Bal de la Abuela"},
  {BrandName: "Delon"},
  {BrandName: "Delore"},
  {BrandName: "Demeter"},
  {BrandName: "Dermacare"},
  {BrandName: "DermaCen"},
  {BrandName: "Dermacolor"},
  {BrandName: "Dermactin-TS"},
  {BrandName: "Dermahealth"},
  {BrandName: "Dermalogica"},
  {BrandName: "Dermaminerals"},
  {BrandName: "Dermapeutics"},
  {BrandName: "Dermaquest"},
  {BrandName: "DermaTech"},
  {BrandName: "DermaWash"},
  {BrandName: "Desert Essence"},
  {BrandName: "Designer Skin"},
  {BrandName: "Designline"},
  {BrandName: "DESITIN"},
  {BrandName: "DHC"},
  {BrandName: "Dial"},
  {BrandName: "Diamond Shine"},
  {BrandName: "Dis-Chem"},
  {BrandName: "Disney Cars"},
  {BrandName: "Disney Finding Dory"},
  {BrandName: "Disney Frozen"},
  {BrandName: "Disney Junior Doc Mcstuffins"},
  {BrandName: "Disney Junior Minnie Mouse"},
  {BrandName: "Disney Princess"},
  {BrandName: "Dolce & Gabbana"},
  {BrandName: "Dollar General"},
  {BrandName: "Dollar Tree"},
  {BrandName: "Don"},
  {BrandName: "Dongguan Changping Mei Ya Cosmetics Factory"},
  {BrandName: "Donna Michelle"},
  {BrandName: "Dove"},
  {BrandName: "Dr. Brandt"},
  {BrandName: "Dr. Hauschka"},
  {BrandName: "Dr. Jessica Wu"},
  {BrandName: "Dr. Lewinn by Kinerase"},
  {BrandName: "Dr. Nona International"},
  {BrandName: "Dr. Robert Rey"},
  {BrandName: "Dreamworks Dinotrux"},
  {BrandName: "Dreamworks Trolls"},
  {BrandName: "Drunk Elephant"},
  {BrandName: "Duane Reade"},
  {BrandName: "Duo"},
  {BrandName: "DuSharme"},
  {BrandName: "Earth Science"},
  {BrandName: "Earth's Best"},
  {BrandName: "Ed Hardy"},
  {BrandName: "Edge"},
  {BrandName: "EFlow Gelez"},
  {BrandName: "Eight Hour"},
  {BrandName: "Elastiderm"},
  {BrandName: "ELIXIR 7.9"},
  {BrandName: "Elizabeth Arden"},
  {BrandName: "Elizabeth Taylor"},
  {BrandName: "Elysee Scientific Cosmetics"},
  {BrandName: "Em Michelle Phan"},
  {BrandName: "Embassy"},
  {BrandName: "Embellir"},
  {BrandName: "Emporium"},
  {BrandName: "ENNCE BEAUTY"},
  {BrandName: "ENREGIN"},
  {BrandName: "Entier"},
  {BrandName: "Entiere"},
  {BrandName: "Entity"},
  {BrandName: "Entity "},
  {BrandName: "eos Evolution of Smooth"},
  {BrandName: "Equaline"},
  {BrandName: "Equate"},
  {BrandName: "Equatone"},
  {BrandName: "Erbaviva"},
  {BrandName: "ERBORIAN"},
  {BrandName: "ERRE DUE"},
  {BrandName: "ESA"},
  {BrandName: "Escence"},
  {BrandName: "ESN"},
  {BrandName: "esselavenna"},
  {BrandName: "essence Ultime"},
  {BrandName: "Essie"},
  {BrandName: "Estee Lauder"},
  {BrandName: "Eternal Youth"},
  {BrandName: "Eucerin"},
  {BrandName: "EVE LOM"},
  {BrandName: "Every Body"},
  {BrandName: "EXCELON"},
  {BrandName: "Exchange Select"},
  {BrandName: "Exel "},
  {BrandName: "Express"},
  {BrandName: "EXTREME"},
  {BrandName: "Exuviance"},
  {BrandName: "EzFlow"},
  {BrandName: "EzFlow "},
  {BrandName: "EzFlow Gelez"},
  {BrandName: "EzFlow Trugel"},
  {BrandName: "Face Fix Mix"},
  {BrandName: "Face Values"},
  {BrandName: "Fairlucent"},
  {BrandName: "Fairy Tales"},
  {BrandName: "Family Dollar"},
  {BrandName: "Fashion Fair"},
  {BrandName: "FC5"},
  {BrandName: "Feeling Beautiful"},
  {BrandName: "FELPS PROFESSIONAL "},
  {BrandName: "Femme Couture"},
  {BrandName: "Femme Couture "},
  {BrandName: "FENTY BEAUTY"},
  {BrandName: "Festivity"},
  {BrandName: "Fillerina"},
  {BrandName: "Fillerina Plus"},
  {BrandName: "Fina"},
  {BrandName: "Fing'rs"},
  {BrandName: "FingerPaints"},
  {BrandName: "FIRA"},
  {BrandName: "FLAUNT"},
  {BrandName: "Flirt"},
  {BrandName: "Forever Florals"},
  {BrandName: "FORMULA X"},
  {BrandName: "FOUND"},
  {BrandName: "Fran Wilson"},
  {BrandName: "Frank Body"},
  {BrandName: "Freeze 24/7"},
  {BrandName: "Fresh"},
  {BrandName: "Fresh beauty"},
  {BrandName: "Fright Night"},
  {BrandName: "Fruits & Passion"},
  {BrandName: "Frutique"},
  {BrandName: "Gap Kids"},
  {BrandName: "Gap Outlet"},
  {BrandName: "Garden of Ireland"},
  {BrandName: "Garnier"},
  {BrandName: "Gelaze"},
  {BrandName: "Gelicity Skin Technology"},
  {BrandName: "Gelish"},
  {BrandName: "Gelish Mini"},
  {BrandName: "Gena"},
  {BrandName: "Generic Value Products"},
  {BrandName: "Germ-X"},
  {BrandName: "GERMAINE DE CAPUCCINI"},
  {BrandName: "GiGi"},
  {BrandName: "Giorgio Armani"},
  {BrandName: "Giorgio Beverly Hills"},
  {BrandName: "Giovanni"},
  {BrandName: "Givenchy"},
  {BrandName: "Glee"},
  {BrandName: "Gleem"},
  {BrandName: "Gliss Kur "},
  {BrandName: "glo minerals"},
  {BrandName: "glo therapeutics "},
  {BrandName: "GLOBAL SILHOUETTE"},
  {BrandName: "Glover's"},
  {BrandName: "GlyMed Plus"},
  {BrandName: "GO SMiLE"},
  {BrandName: "GO247"},
  {BrandName: "GOJO"},
  {BrandName: "Gold Bond"},
  {BrandName: "GOLDEN BEACH"},
  {BrandName: "Goldwell"},
  {BrandName: "GOOCHIE"},
  {BrandName: "Good 'N Natural"},
  {BrandName: "Good Sense"},
  {BrandName: "Good Skin"},
  {BrandName: "Goodier"},
  {BrandName: "Got2b"},
  {BrandName: "Grand Touch"},
  {BrandName: "Grassroots"},
  {BrandName: "Great Clips"},
  {BrandName: "Great Clips Detour"},
  {BrandName: "Great Clips Solutions"},
  {BrandName: "Grecian Formula 16"},
  {BrandName: "Grecian Plus"},
  {BrandName: "Greenbrier International, Inc."},
  {BrandName: "Gucci"},
  {BrandName: "GUERLAIN"},
  {BrandName: "Guess"},
  {BrandName: "Gwen Stefani"},
  {BrandName: "Hada Labo Tokyo"},
  {BrandName: "Hair Chemist"},
  {BrandName: "Hair Food"},
  {BrandName: "Hair Off"},
  {BrandName: "Hair One"},
  {BrandName: "Hair Plump"},
  {BrandName: "Hair Rep"},
  {BrandName: "HairPlay"},
  {BrandName: "HairTec"},
  {BrandName: "Halle Berry Pure Orchid"},
  {BrandName: "Halle Berry Reveal"},
  {BrandName: "Halle by Halle Berry"},
  {BrandName: "Hallmark Cards"},
  {BrandName: "Hannaford"},
  {BrandName: "Hard Candy"},
  {BrandName: "Harmon"},
  {BrandName: "Harmon Face Values"},
  {BrandName: "Harmony"},
  {BrandName: "Hawaiian Tropic"},
  {BrandName: "Hayashi Tecnica"},
  {BrandName: "HCE"},
  {BrandName: "Health Splt's Progesterone Cream"},
  {BrandName: "Healthy Accents"},
  {BrandName: "Heavy Duty Hand Cleanser"},
  {BrandName: "Heb"},
  {BrandName: "Heel to Toe"},
  {BrandName: "Helena Rubenstein"},
  {BrandName: "Hello Kitty"},
  {BrandName: "HEMPZ"},
  {BrandName: "Heno De Pravia"},
  {BrandName: "Herbal 3"},
  {BrandName: "Herbal Aloe"},
  {BrandName: "Herbal Authority"},
  {BrandName: "Herbal Essences"},
  {BrandName: "Herbal Skin Solutions"},
  {BrandName: "Herpecin-L"},
  {BrandName: "Hershey's"},
  {BrandName: "Hill Country Essentials"},
  {BrandName: "HILLYARD"},
  {BrandName: "Himalaya"},
  {BrandName: "HIPPIE CHICK"},
  {BrandName: "Hissyfit"},
  {BrandName: "Home Health"},
  {BrandName: "Hot Topic"},
  {BrandName: "Houbigant"},
  {BrandName: "Hourglass Cosmetics"},
  {BrandName: "Howard Johnson"},
  {BrandName: "Hy-Vee"},
  {BrandName: "I COLONIALI"},
  {BrandName: "I Dew Care"},
  {BrandName: "I Love"},
  {BrandName: "i.color"},
  {BrandName: "i.Luminate "},
  {BrandName: "IBD"},
  {BrandName: "IBD "},
  {BrandName: "IBD Gelac"},
  {BrandName: "IBD Just Gel"},
  {BrandName: "ICE Hair"},
  {BrandName: "ICE Spiker"},
  {BrandName: "Icing"},
  {BrandName: "Ideal"},
  {BrandName: "IGORA"},
  {BrandName: "IGORA COLOR10"},
  {BrandName: "IGORA PERSONALITY"},
  {BrandName: "IGORA VIVIANCE"},
  {BrandName: "Illumination Enterprise Minions"},
  {BrandName: "Image Essentials"},
  {BrandName: "iN-gredients"},
  {BrandName: "Infusion"},
  {BrandName: "Infusium"},
  {BrandName: "Inis"},
  {BrandName: "Innisfree"},
  {BrandName: "innisfree "},
  {BrandName: "Innosys"},
  {BrandName: "Innovative Skincare"},
  {BrandName: "INSIGHT"},
  {BrandName: "Institute Swiss"},
  {BrandName: "Intelligence"},
  {BrandName: "Internal Harmony"},
  {BrandName: "Ion"},
  {BrandName: "Ionil T"},
  {BrandName: "IOPE"},
  {BrandName: "IOPE "},
  {BrandName: "Iredale Mineral Cosmetics Skin Care"},
  {BrandName: "Irene Gari"},
  {BrandName: "Irish Spring"},
  {BrandName: "Its a Fine Line"},
  {BrandName: "Its All in the Eyes          "},
  {BrandName: "Its Happy Bunny"},
  {BrandName: "Its So Easy"},
  {BrandName: "Jafra"},
  {BrandName: "Jan Marini Skin Research"},
  {BrandName: "Japonesque"},
  {BrandName: "Jason"},
  {BrandName: "Jenna Hipp"},
  {BrandName: "Jergens"},
  {BrandName: "Jhirmack"},
  {BrandName: "Jil Sander Stylessence"},
  {BrandName: "JK Jemma Kidd"},
  {BrandName: "JLo Glow After Dark"},
  {BrandName: "Jo Malone"},
  {BrandName: "John Frieda"},
  {BrandName: "John Paul Mitchell Systems"},
  {BrandName: "JOHNSON'S"},
  {BrandName: "Joico"},
  {BrandName: "JORDANA"},
  {BrandName: "JR Watkins"},
  {BrandName: "Juice Beauty"},
  {BrandName: "Juicy Couture"},
  {BrandName: "Jupier"},
  {BrandName: "Jurlique"},
  {BrandName: "Just for Girls"},
  {BrandName: "Kadus"},
  {BrandName: "Kama Sutra"},
  {BrandName: "Kandesn"},
  {BrandName: "KANEBO"},
  {BrandName: "KAT VON D"},
  {BrandName: "Kate Somerville"},
  {BrandName: "Kenneth Cole Black"},
  {BrandName: "Kenneth Cole Connected"},
  {BrandName: "Kenneth Cole Reaction"},
  {BrandName: "Kenneth Cole RSVP"},
  {BrandName: "Kenneth Cole Vintage Black"},
  {BrandName: "Kenra"},
  {BrandName: "KENZO"},
  {BrandName: "KeraCare"},
  {BrandName: "Kerastase"},
  {BrandName: "Kevin Murphy"},
  {BrandName: "Kiehl's"},
  {BrandName: "Kinerase"},
  {BrandName: "KINGS AND QUEENS"},
  {BrandName: "Kiss"},
  {BrandName: "Klar & Danver"},
  {BrandName: "KLEENEX"},
  {BrandName: "KORRES NATURAL PRODUCTS"},
  {BrandName: "Kristofer Buckle"},
  {BrandName: "Kroger"},
  {BrandName: "Kryolan"},
  {BrandName: "L.A. Colors"},
  {BrandName: "L.A. Girl"},
  {BrandName: "L'BEL"},
  {BrandName: "L'OCCITANE"},
  {BrandName: "L'OCCITANE AU BRESIL"},
  {BrandName: "L'OCCITANE EN PROVENCE"},
  {BrandName: "L'Oreal"},
  {BrandName: "La Biosthetique"},
  {BrandName: "La Mer"},
  {BrandName: "LA PERLA"},
  {BrandName: "La Prairie"},
  {BrandName: "La Roche-Posay"},
  {BrandName: "Lab Series"},
  {BrandName: "label.m"},
  {BrandName: "Laboratoire Remede"},
  {BrandName: "Lac Sensation"},
  {BrandName: "Lamas  "},
  {BrandName: "LaNatura"},
  {BrandName: "Lancaster"},
  {BrandName: "Lancome"},
  {BrandName: "Laneige"},
  {BrandName: "LANVIN PARIS"},
  {BrandName: "Lash Love"},
  {BrandName: "LAURA MERCIER"},
  {BrandName: "LAUREN HUTTON"},
  {BrandName: "Lelan Vital"},
  {BrandName: "Les Plaisirs Nature"},
  {BrandName: "LESSE"},
  {BrandName: "Lever 2000"},
  {BrandName: "Lever 2000 Vaseline"},
  {BrandName: "Lexi"},
  {BrandName: "Life"},
  {BrandName: "Light Elegance"},
  {BrandName: "Lila"},
  {BrandName: "Lip Smacker"},
  {BrandName: "LiPigments"},
  {BrandName: "Lipstick Queen"},
  {BrandName: "Lise Watier Cosmtiques Inc."},
  {BrandName: "Little Luxuries"},
  {BrandName: "Living Source"},
  {BrandName: "Liz Claiborne"},
  {BrandName: "Look Beauty"},
  {BrandName: "Love My Smile"},
  {BrandName: "LOVE STRUCK"},
  {BrandName: "Love U X"},
  {BrandName: "Lpiz Labial "},
  {BrandName: "Lubriderm"},
  {BrandName: "Lucero"},
  {BrandName: "Lucrece"},
  {BrandName: "Lumene"},
  {BrandName: "Luminelle"},
  {BrandName: "Luminelle Folk Passion"},
  {BrandName: "Lush"},
  {BrandName: "MAC"},
  {BrandName: "Madre Perla De Ultratez"},
  {BrandName: "MAJA"},
  {BrandName: "MAKE UP FOR EVER"},
  {BrandName: "Malin & Goetz"},
  {BrandName: "Mambo"},
  {BrandName: "Mamonde"},
  {BrandName: "Mamonde "},
  {BrandName: "Mannatech"},
  {BrandName: "Marc Jacobs"},
  {BrandName: "MARCHESA"},
  {BrandName: "Mariah Carey"},
  {BrandName: "Marianna Industries"},
  {BrandName: "MARK"},
  {BrandName: "Market Basket"},
  {BrandName: "Market Spa"},
  {BrandName: "Marriott"},
  {BrandName: "Marvel Avengers"},
  {BrandName: "Marvel Spiderman"},
  {BrandName: "Mary Kay"},
  {BrandName: "MasterCuts"},
  {BrandName: "Match Race"},
  {BrandName: "Matrix"},
  {BrandName: "MAVALA"},
  {BrandName: "Maybelline"},
  {BrandName: "McKesson"},
  {BrandName: "MDSolarSciences"},
  {BrandName: "Meaningful Beauty"},
  {BrandName: "MED3"},
  {BrandName: "Medi-Dan"},
  {BrandName: "Medi-Pak"},
  {BrandName: "Meijer"},
  {BrandName: "MELVITA"},
  {BrandName: "Men Fresh"},
  {BrandName: "Menard"},
  {BrandName: "Meringue"},
  {BrandName: "Merle Norman"},
  {BrandName: "Merle Roberts"},
  {BrandName: "Methode Physiodermie"},
  {BrandName: "Michael Kors"},
  {BrandName: "Michel Design Works"},
  {BrandName: "MICRELL"},
  {BrandName: "Microbond"},
  {BrandName: "MILANI"},
  {BrandName: "Milk"},
  {BrandName: "Mineral Mask"},
  {BrandName: "Miracle Plus"},
  {BrandName: "Miralla's Spa"},
  {BrandName: "Mirra Renew"},
  {BrandName: "Missoni"},
  {BrandName: "Mizani"},
  {BrandName: "MOCARA"},
  {BrandName: "MOCARA SERUM   "},
  {BrandName: "Modere"},
  {BrandName: "Moisture Defense"},
  {BrandName: "Molton Brown"},
  {BrandName: "Monkey Butt"},
  {BrandName: "MONOI DE TAHITI"},
  {BrandName: "Monster High"},
  {BrandName: "Montagne Jeunesse"},
  {BrandName: "MOR Cosmetics"},
  {BrandName: "Morgan Taylor"},
  {BrandName: "Motions"},
  {BrandName: "Mountain Dew"},
  {BrandName: "Mountain Falls"},
  {BrandName: "Moxie"},
  {BrandName: "MUA"},
  {BrandName: "Murad"},
  {BrandName: "Mustela"},
  {BrandName: "My Joy Collection"},
  {BrandName: "Mystic Divine"},
  {BrandName: "N'RAGE"},
  {BrandName: "Nail Bliss"},
  {BrandName: "Nail Envy"},
  {BrandName: "Nail Life"},
  {BrandName: "Nail Magic"},
  {BrandName: "Nail Optimizer"},
  {BrandName: "Nail Pops"},
  {BrandName: "Nail Rx"},
  {BrandName: "Nail Spa"},
  {BrandName: "Nail Tek"},
  {BrandName: "Nailene"},
  {BrandName: "NARS"},
  {BrandName: "Native Tan"},
  {BrandName: "Natura Bisse"},
  {BrandName: "Natural Advantage"},
  {BrandName: "Natural Concepts"},
  {BrandName: "Natural Wealth"},
  {BrandName: "Naturale Essential"},
  {BrandName: "Nature's Bounty"},
  {BrandName: "Nature's Gate"},
  {BrandName: "Nature's Sunshine"},
  {BrandName: "Natures Intent"},
  {BrandName: "Nautica"},
  {BrandName: "NeoStrata"},
  {BrandName: "Nestle "},
  {BrandName: "Neutrogena"},
  {BrandName: "New Directions Aromatics"},
  {BrandName: "Neways"},
  {BrandName: "NEXT 1"},
  {BrandName: "Nexxus"},
  {BrandName: "NFL"},
  {BrandName: "Nice Touch"},
  {BrandName: "Nickelodeon"},
  {BrandName: "Nicki Minaj"},
  {BrandName: "NINA RICCI"},
  {BrandName: "Nioxin"},
  {BrandName: "Nippon Menard Cosmetic Co., Ltd."},
  {BrandName: "Nirvae"},
  {BrandName: "Nivea"},
  {BrandName: "NO"},
  {BrandName: "No Bare Brows"},
  {BrandName: "No Dark Shadows"},
  {BrandName: "No Lift Nails"},
  {BrandName: "No7"},
  {BrandName: "NOEVIR"},
  {BrandName: "Nooni"},
  {BrandName: "Nourifusion"},
  {BrandName: "Nouvelle"},
  {BrandName: "Novelty, Inc."},
  {BrandName: "NSI"},
  {BrandName: "Nu Skin"},
  {BrandName: "Nudestix"},
  {BrandName: "Nutra Nail"},
  {BrandName: "Nutraderm Cream"},
  {BrandName: "Nutraderm Lotion"},
  {BrandName: "Nutraplus Cream"},
  {BrandName: "Nutri-Rich"},
  {BrandName: "Nutrimetics"},
  {BrandName: "NutriMinC RE9"},
  {BrandName: "NUTRITION BODY"},
  {BrandName: "Nutrition Warehouse"},
  {BrandName: "NUXE"},
  {BrandName: "NYC - New York Color"},
  {BrandName: "NYX"},
  {BrandName: "Ocean Potion Naturals"},
  {BrandName: "Odd Molly"},
  {BrandName: "Ojon"},
  {BrandName: "Olay"},
  {BrandName: "Old Navy"},
  {BrandName: "Old Spice"},
  {BrandName: "Olive Oil Girls"},
  {BrandName: "Omni"},
  {BrandName: "One by KOS"},
  {BrandName: "ONE RANGE "},
  {BrandName: "OPI"},
  {BrandName: "ORGANIC WAY"},
  {BrandName: "Origins"},
  {BrandName: "Orly"},
  {BrandName: "Osis"},
  {BrandName: "Othine"},
  {BrandName: "Ovale"},
  {BrandName: "Owl"},
  {BrandName: "Oxy"},
  {BrandName: "PACO RABANNE"},
  {BrandName: "Palladio"},
  {BrandName: "Palmer's"},
  {BrandName: "Palmolive"},
  {BrandName: "Panrosa"},
  {BrandName: "Pantene"},
  {BrandName: "Pati DuBroff"},
  {BrandName: "Paula's Choice"},
  {BrandName: "Paula's Choice "},
  {BrandName: "PAYOT"},
  {BrandName: "PAYOT LE CORPS"},
  {BrandName: "PAYOT LES CORRECTRICES"},
  {BrandName: "PAYOT LES PURIFIANTES"},
  {BrandName: "PAYOT MY PAYOT"},
  {BrandName: "PAYOT OPTIMALE"},
  {BrandName: "PCA Skin"},
  {BrandName: "Pearl Prescriptives"},
  {BrandName: "Pearlosophy"},
  {BrandName: "Pedix"},
  {BrandName: "Peelu"},
  {BrandName: "Peeps "},
  {BrandName: "Penhaligon's"},
  {BrandName: "Peppa Pig"},
  {BrandName: "Perfect skin"},
  {BrandName: "Perfectly Pure"},
  {BrandName: "Perfjohn"},
  {BrandName: "Perricone MD"},
  {BrandName: "Perron Rigot"},
  {BrandName: "Personal Elements"},
  {BrandName: "Philosophy"},
  {BrandName: "Physicians Formula"},
  {BrandName: "Physiocoiffeur"},
  {BrandName: "Pink Dreams"},
  {BrandName: "Pinnacle Cosmetics"},
  {BrandName: "Plaisir Nature"},
  {BrandName: "Planet Beach"},
  {BrandName: "Playboy"},
  {BrandName: "Plus White"},
  {BrandName: "Podiatrist's Formula"},
  {BrandName: "Pond's"},
  {BrandName: "POP"},
  {BrandName: "POP Beauty"},
  {BrandName: "Popsicle"},
  {BrandName: "Poshe"},
  {BrandName: "Power Stick"},
  {BrandName: "PRADA"},
  {BrandName: "Prai Beauty"},
  {BrandName: "Premier Value"},
  {BrandName: "Prescriptives"},
  {BrandName: "Prevage"},
  {BrandName: "PrimaDerm"},
  {BrandName: "Prime & Proper"},
  {BrandName: "PRIME SOURCE"},
  {BrandName: "PRIMORY"},
  {BrandName: "PRIORI"},
  {BrandName: "Pro White & Professional"},
  {BrandName: "Proactiv"},
  {BrandName: "ProClean"},
  {BrandName: "ProLinc"},
  {BrandName: "PROLINK"},
  {BrandName: "ProStrong"},
  {BrandName: "Prosys"},
  {BrandName: "PROVON"},
  {BrandName: "Proxima"},
  {BrandName: "Publix"},
  {BrandName: "Pucker Ups"},
  {BrandName: "pump-it-up"},
  {BrandName: "PUR LUXE"},
  {BrandName: "pur-lisse"},
  {BrandName: "Pure & Basic"},
  {BrandName: "PURELL"},
  {BrandName: "PUREOLOGY"},
  {BrandName: "Purist"},
  {BrandName: "Puritan's Pride"},
  {BrandName: "Purminerals"},
  {BrandName: "Push Pop"},
  {BrandName: "Qiora"},
  {BrandName: "QT"},
  {BrandName: "Quality Choice"},
  {BrandName: "Quality Inn"},
  {BrandName: "Quantum Colors"},
  {BrandName: "Que Bella"},
  {BrandName: "Queen Helene"},
  {BrandName: "QUELQUES NOTES D'AMOUR"},
  {BrandName: "Raddison"},
  {BrandName: "RAIN"},
  {BrandName: "Rapha"},
  {BrandName: "RareMinerals"},
  {BrandName: "Raven"},
  {BrandName: "RAYZ"},
  {BrandName: "RE9 Advanced"},
  {BrandName: "RECETTE MERVEILLEUSE"},
  {BrandName: "Red Carpet"},
  {BrandName: "Redken"},
  {BrandName: "Regal"},
  {BrandName: "Regenetresse"},
  {BrandName: "Regis"},
  {BrandName: "Rejuva"},
  {BrandName: "Reliable"},
  {BrandName: "Renown"},
  {BrandName: "Retinol Max"},
  {BrandName: "Retinol-X"},
  {BrandName: "Retocador de canas"},
  {BrandName: "Revelage"},
  {BrandName: "Revision Skincare"},
  {BrandName: "Revitalash"},
  {BrandName: "Revlon"},
  {BrandName: "Rexaline"},
  {BrandName: "Rexall"},
  {BrandName: "Riche Creme"},
  {BrandName: "Rick and Morty"},
  {BrandName: "Rimmel - London"},
  {BrandName: "Rite Aid"},
  {BrandName: "RITUALS"},
  {BrandName: "RITUELS BOTANICAL"},
  {BrandName: "RMS"},
  {BrandName: "Robin McGraw Revelation"},
  {BrandName: "RoC"},
  {BrandName: "Rock and Republic"},
  {BrandName: "Rockaholic"},
  {BrandName: "Rodan + Fields"},
  {BrandName: "Rodeway"},
  {BrandName: "Rosaclear"},
  {BrandName: "Roux"},
  {BrandName: "Royal Crown"},
  {BrandName: "Royal Essential"},
  {BrandName: "Rubor"},
  {BrandName: "Ruby Kisses"},
  {BrandName: "Rusk"},
  {BrandName: "S-Factor"},
  {BrandName: "SA Lidl"},
  {BrandName: "Sacred Elements"},
  {BrandName: "Safeguard"},
  {BrandName: "Safeway"},
  {BrandName: "salerm cosmetics"},
  {BrandName: "Sally Girl"},
  {BrandName: "Sally Hansen"},
  {BrandName: "Salon Care"},
  {BrandName: "Salon Perfect"},
  {BrandName: "Samy"},
  {BrandName: "Sanctuary Spa Covent Garden Bidadari"},
  {BrandName: "Sanctuary Spa Covent Garden Mande Lular"},
  {BrandName: "Sarah Jessica Parker"},
  {BrandName: "Saranari"},
  {BrandName: "Sassy & Chic"},
  {BrandName: "Satin Hands"},
  {BrandName: "Sation"},
  {BrandName: "Save Your Sole"},
  {BrandName: "Savvy"},
  {BrandName: "SB"},
  {BrandName: "Schick"},
  {BrandName: "SCOTT"},
  {BrandName: "Scruples"},
  {BrandName: "SCUDERIA FERRARI"},
  {BrandName: "Sea Enzyme Ultra Umbrella"},
  {BrandName: "Sears"},
  {BrandName: "Sebastian"},
  {BrandName: "SEBO VEGETAL"},
  {BrandName: "SEBO VEGETAL "},
  {BrandName: "Seche Vite"},
  {BrandName: "Secret Agent"},
  {BrandName: "Sei Bella"},
  {BrandName: "SEKKISEI"},
  {BrandName: "Select Brand"},
  {BrandName: "Selsun Blue"},
  {BrandName: "Selsun Naturals"},
  {BrandName: "SENSAI"},
  {BrandName: "SensatioNail"},
  {BrandName: "Senscience"},
  {BrandName: "Sentara"},
  {BrandName: "SEPHORA"},
  {BrandName: "SEPHORA FORMULA X"},
  {BrandName: "Serum"},
  {BrandName: "SERUM VEGETAL"},
  {BrandName: "Sesame Street"},
  {BrandName: "Sexy Bath and Body"},
  {BrandName: "Shania by Stetson"},
  {BrandName: "Shape It Up"},
  {BrandName: "Shea Butter"},
  {BrandName: "Sheila"},
  {BrandName: "SHELO NABEL"},
  {BrandName: "Shift"},
  {BrandName: "Shine In"},
  {BrandName: "Shining Stars"},
  {BrandName: "SHISEIDO"},
  {BrandName: "Shop Rite"},
  {BrandName: "Shopkins"},
  {BrandName: "Shopko"},
  {BrandName: "Short Sexy Hair"},
  {BrandName: "Shu Uemura"},
  {BrandName: "SIGNATRY"},
  {BrandName: "Signature Care"},
  {BrandName: "SILHOUETTE GLOBALLE"},
  {BrandName: "Simple"},
  {BrandName: "Simply U"},
  {BrandName: "SINFUL COLORS"},
  {BrandName: "Singuladerm"},
  {BrandName: "SISLEY - PARIS"},
  {BrandName: "SK-II"},
  {BrandName: "Skin Nutrition with Phytomins"},
  {BrandName: "Skin Republic"},
  {BrandName: "Skin Strategies"},
  {BrandName: "SKIN SYSTEM"},
  {BrandName: "Skin Tight"},
  {BrandName: "Skin Vitamins"},
  {BrandName: "Skincare LdeL Cosmetics Retinol"},
  {BrandName: "SKINCEUTICALS"},
  {BrandName: "SkinLab"},
  {BrandName: "Skinlogics Gold"},
  {BrandName: "SkinMedica"},
  {BrandName: "Skinn"},
  {BrandName: "Skintimate"},
  {BrandName: "Sleep Inn"},
  {BrandName: "Smackers"},
  {BrandName: "Smashbox"},
  {BrandName: "Smooth 'n Shine"},
  {BrandName: "SNP"},
  {BrandName: "SO BRONZE"},
  {BrandName: "So Gorgeous"},
  {BrandName: "Soap & Glory"},
  {BrandName: "Sofia"},
  {BrandName: "Soft & Beautiful"},
  {BrandName: "Softlips"},
  {BrandName: "Softsoap"},
  {BrandName: "Soin vegetal"},
  {BrandName: "Soma"},
  {BrandName: "Sombra"},
  {BrandName: "Sonoma Spa"},
  {BrandName: "Sonya Dakar"},
  {BrandName: "SOTHYS"},
  {BrandName: "Soul Mate"},
  {BrandName: "Sound Body"},
  {BrandName: "SPA BATH"},
  {BrandName: "Spa Mask"},
  {BrandName: "Splendor"},
  {BrandName: "SSC"},
  {BrandName: "St. Ives"},
  {BrandName: "Stendhal"},
  {BrandName: "Stila"},
  {BrandName: "Stormy Weather"},
  {BrandName: "Strawberry Shortcake"},
  {BrandName: "Streaks 'N' Tips"},
  {BrandName: "STREET DIVA"},
  {BrandName: "StripLac"},
  {BrandName: "StriVectin"},
  {BrandName: "STRUCTURE + MANAGE"},
  {BrandName: "Studio 35"},
  {BrandName: "Studio Gear"},
  {BrandName: "Style Sexy Hair "},
  {BrandName: "Styliste Ultime"},
  {BrandName: "Suave"},
  {BrandName: "Sudden Change"},
  {BrandName: "Sultry"},
  {BrandName: "SULWHASOO"},
  {BrandName: "Sumita Beauty"},
  {BrandName: "Sun Care System"},
  {BrandName: "Sun Star"},
  {BrandName: "Sundown Naturals"},
  {BrandName: "Sunflower Nature's Spirit"},
  {BrandName: "Sunflowers"},
  {BrandName: "Sunforgettable"},
  {BrandName: "Sunglitz"},
  {BrandName: "Sunmark"},
  {BrandName: "Sunrise Greetings"},
  {BrandName: "Sunsilk"},
  {BrandName: "Super 8"},
  {BrandName: "SUPER STAR"},
  {BrandName: "SuperNail"},
  {BrandName: "SuperNail "},
  {BrandName: "Surgi"},
  {BrandName: "Swan"},
  {BrandName: "Swanson"},
  {BrandName: "Swash"},
  {BrandName: "Swedish Beauty"},
  {BrandName: "T-ZONE"},
  {BrandName: "Tahitian Noni Tahiti Trim Plan 40"},
  {BrandName: "Tammy Taylor"},
  {BrandName: "Tan Luxe"},
  {BrandName: "Tanwise"},
  {BrandName: "Target"},
  {BrandName: "tarte"},
  {BrandName: "Task"},
  {BrandName: "TAUNT"},
  {BrandName: "TEMPT"},
  {BrandName: "Tend Skin"},
  {BrandName: "TEOXANE"},
  {BrandName: "Thalia Sodi"},
  {BrandName: "The Art of Shaving"},
  {BrandName: "The Body Shop"},
  {BrandName: "The BrowGal By Tonya Crooks"},
  {BrandName: "The Color Workshop"},
  {BrandName: "THE ESSENCE OF NATURE"},
  {BrandName: "theBalm"},
  {BrandName: "Therabath"},
  {BrandName: "THIERRY MUGLER"},
  {BrandName: "Three Flowers"},
  {BrandName: "Threshold "},
  {BrandName: "Thymes"},
  {BrandName: "TIGI"},
  {BrandName: "TimeWise"},
  {BrandName: "Tom's of Maine"},
  {BrandName: "Tommy Hilfiger"},
  {BrandName: "Tone"},
  {BrandName: "Too Faced"},
  {BrandName: "TopCare"},
  {BrandName: "TOUGH GUY"},
  {BrandName: "Trader Joe's "},
  {BrandName: "TRADITION DE HAMMAM"},
  {BrandName: "Travelodge"},
  {BrandName: "TRESemme"},
  {BrandName: "Tressa"},
  {BrandName: "Triple S"},
  {BrandName: "Trish McEvoy"},
  {BrandName: "Trivani"},
  {BrandName: "Trucco"},
  {BrandName: "True Dimensions"},
  {BrandName: "True Love"},
  {BrandName: "TRUETOUCH"},
  {BrandName: "Tsukika"},
  {BrandName: "Tweezerman"},
  {BrandName: "UHS "},
  {BrandName: "Ulta"},
  {BrandName: "Ultra Labs"},
  {BrandName: "Ultrabrite"},
  {BrandName: "Ultraflesh"},
  {BrandName: "UNA"},
  {BrandName: "Unite Eurotherapy"},
  {BrandName: "Up & Up"},
  {BrandName: "Up&Up"},
  {BrandName: "Upper Canada Soap"},
  {BrandName: "Urban Decay "},
  {BrandName: "Urban Outfitters"},
  {BrandName: "V76 by Vaughn"},
  {BrandName: "Vanicream"},
  {BrandName: "Vaseline"},
  {BrandName: "VEET"},
  {BrandName: "Velvachol"},
  {BrandName: "Venique"},
  {BrandName: "Venus"},
  {BrandName: "Vera Wang"},
  {BrandName: "Vero K-PAK Color"},
  {BrandName: "Vi-Jon Professionals"},
  {BrandName: "Vi-Jon, Inc"},
  {BrandName: "Vi-Jon, Inc."},
  {BrandName: "Vibrant Sexy Hair"},
  {BrandName: "Vichy"},
  {BrandName: "Victoria's Secret Beauty"},
  {BrandName: "Viktor & Rolf"},
  {BrandName: "Vintage Glam"},
  {BrandName: "Vista"},
  {BrandName: "Visual Changes"},
  {BrandName: "Vital Care"},
  {BrandName: "Vitamin World"},
  {BrandName: "Vivir  "},
  {BrandName: "Wal-Mart"},
  {BrandName: "Walgreens"},
  {BrandName: "Wanderlove"},
  {BrandName: "WaxieCare"},
  {BrandName: "Web"},
  {BrandName: "Wella"},
  {BrandName: "Wen"},
  {BrandName: "Western Family"},
  {BrandName: "Wet n Wild"},
  {BrandName: "White Botanical"},
  {BrandName: "White Tea"},
  {BrandName: "Whiter Image"},
  {BrandName: "Winco"},
  {BrandName: "Wit & Wisdom"},
  {BrandName: "Woody's"},
  {BrandName: "YB"},
  {BrandName: "Yes to Blueberries"},
  {BrandName: "Yes to Carrots"},
  {BrandName: "Yes to Cucumbers"},
  {BrandName: "Yes to Grapefruit"},
  {BrandName: "Yes to Tomatoes"},
  {BrandName: "Yiwu Aris Cosmetic Manufactory"},
  {BrandName: "YL"},
  {BrandName: "Ylang-Ylang"},
  {BrandName: "Yoanna"},
  {BrandName: "YON KA"},
  {BrandName: "Young Nails"},
  {BrandName: "Youthair"},
  {BrandName: "Yves Rocher - BAUME LEVRES"},
  {BrandName: "Yves Rocher - BOTANICAL COLOR"},
  {BrandName: "Yves Rocher - Cocoa collection"},
  {BrandName: "Yves Rocher - COLLECTION NOEL"},
  {BrandName: "Yves Rocher Inc."},
  {BrandName: "Yves Saint Laurent"},
  {BrandName: "ZACH'S WAX"},
  {BrandName: "Zalan Products, Inc."},
  {BrandName: "Zelens"},
  {BrandName: "Zest"},
  {BrandName: "Zhejiang Yiwu Lucy Cosmetics Co.,Ltd."},
  {BrandName: "Zia Natural Skincare"},
  {BrandName: "ZO Skiin Health"},
  {BrandName: "ZO Skin Health"},
  {BrandName: "Zona Rosa"},
  {BrandName: "Zuri"},
  {BrandName: "Zuri Brazil"},
  {BrandName: "Zuri Flawless"},
  {BrandName: "Zuri Naturally Sheer"}
])
